#!/usr/bin/env python

Import('env')
Import("env_modules")

module_obj = []

env_error_handler = env_modules.Clone()
env_error_handler.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
